# This workflow will do a clean installation of node dependencies, cache/restore them,
# and build the source code on node version 10.x and run tests using pytest and Selenium via Conda.
name: Pytests Using Selenium in Conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Tests:

    runs-on: ubuntu-latest

    env:
      DB_CONN: ${{secrets.DB_CONN}}

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install conda and dependencies in conda env
        run: $CONDA/bin/conda env update --file "$GITHUB_WORKSPACE/tests/pytests/environment.yml" --name base
      - name: Test with pytest
        run: |
          npm start &
          $CONDA/bin/pytest -s -n=6 --capture=tee-sys
